import { motion } from 'framer-motion';
import { 
  Terminal, BarChart2, BrainCircuit, Layers, ChevronRight, RefreshCw, Activity 
} from 'lucide-react';
import { renderMarkdown } from '../utils/markdown.js';

export default function RepoDashboard({ repo, onSelectSuggestion, summaryData, isLoadingSummary, onRefreshSummary }) {
  if (isLoadingSummary) {
    return (
      <motion.div 
        initial={{ opacity: 0 }} 
        animate={{ opacity: 1 }} 
        exit={{ opacity: 0 }} 
        className="w-full max-w-4xl mx-auto p-6 space-y-6 pt-10"
      >
        <div className="h-7 bg-slate-800/40 rounded-lg w-1/3 animate-pulse"></div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="h-20 bg-slate-800/30 rounded-xl border border-white/[0.02] animate-pulse"></div>
          <div className="h-20 bg-slate-800/30 rounded-xl border border-white/[0.02] animate-pulse"></div>
          <div className="h-20 bg-slate-800/30 rounded-xl border border-white/[0.02] animate-pulse"></div>
        </div>
        <div className="h-80 bg-slate-800/20 rounded-2xl border border-white/[0.02] animate-pulse"></div>
      </motion.div>
    );
  }

  if (!summaryData) {
    return (
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-col items-center justify-center p-16 text-center">
        <Activity size={32} className="text-indigo-400 animate-spin mb-4" />
        <p className="text-slate-400 text-sm">Failed to generate codebase profile summary.</p>
        <button onClick={onRefreshSummary} className="mt-4 px-4 py-2 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-xl text-xs font-semibold flex items-center gap-1.5 hover:bg-indigo-500/20 transition-all">
          <RefreshCw size={12} /> Try Again
        </button>
      </motion.div>
    );
  }

  const { summary, metadata } = summaryData;
  const languages = metadata?.languages || [];
  const totalChunks = metadata?.total_chunks || 0;
  const filesSampled = metadata?.files_sampled || 0;

  const SUGGESTIONS = [
    { text: "Explain the overall architecture and system design of this repo.", label: "Architecture" },
    { text: "What is the main entry point and startup flow?", label: "Entry Point" },
    { text: "Identify key modules and their core responsibilities.", label: "Modules" },
    { text: "What patterns and architectural decisions stand out here?", label: "Design Patterns" }
  ];

  return (
    <motion.div 
      variants={{
        hidden: { opacity: 0 },
        show: { opacity: 1, transition: { staggerChildren: 0.08 } }
      }}
      initial="hidden" 
      animate="show"
      exit="hidden"
      className="w-full max-w-4xl mx-auto p-6 space-y-8 pt-10"
    >
      {/* Title */}
      <motion.div variants={{ hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0 } }} className="flex justify-between items-center">
        <div>
          <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            <Layers size={18} className="text-indigo-400" />
            Codebase Intelligence Profile
          </h3>
          <p className="text-xs text-slate-400">High-level analysis generated by RepoSage AI</p>
        </div>
        <button 
          onClick={onRefreshSummary} 
          title="Force Re-generate Profile Summary"
          className="p-2 hover:bg-slate-800/80 border border-slate-700/30 text-slate-400 hover:text-white rounded-xl transition flex items-center justify-center"
        >
          <RefreshCw size={14} className="hover:rotate-180 transition-transform duration-500" />
        </button>
      </motion.div>

      {/* Metadata Cards */}
      <motion.div 
        variants={{
          hidden: { opacity: 0 },
          show: { opacity: 1, transition: { staggerChildren: 0.05 } }
        }}
        className="grid grid-cols-1 md:grid-cols-3 gap-4"
      >
        <StatCard 
          icon={<Terminal size={18} className="text-indigo-400" />} 
          title="Vector Index Size" 
          value={`${totalChunks} chunks`}
          desc="AST-parsed code fragments"
        />
        <StatCard 
          icon={<BarChart2 size={18} className="text-purple-400" />} 
          title="Codebase Profiled" 
          value={`${filesSampled} files`}
          desc="Used for architectural summary"
        />
        <StatCard 
          icon={<BrainCircuit size={18} className="text-emerald-400" />} 
          title="Detected Tech Stack" 
          value={languages.join(', ') || 'N/A'}
          desc="Identified source languages"
        />
      </motion.div>

      {/* Summary Content */}
      <motion.div 
        variants={{ hidden: { opacity: 0, y: 15 }, show: { opacity: 1, y: 0 } }}
        className="glass-card glow-hover p-6 border border-white/[0.03] shadow-lg overflow-hidden relative"
      >
        <div className="absolute top-0 left-0 w-full h-[2px] bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 opacity-30"></div>
        <h4 className="text-xs font-bold text-indigo-400 uppercase tracking-widest mb-4">Architecture Summary</h4>
        <div 
          className="prose prose-invert max-w-none text-sm text-slate-300 leading-relaxed space-y-4"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(summary) }} 
        />
      </motion.div>

      {/* Quick Start Suggestions */}
      <motion.div variants={{ hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0 } }} className="space-y-3">
        <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest">Suggested Queries</h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {SUGGESTIONS.map((s, idx) => (
            <motion.div
              whileHover={{ y: -2, scale: 1.01 }}
              transition={{ type: "spring", stiffness: 400, damping: 30 }}
              key={idx}
              onClick={() => onSelectSuggestion(s.text)}
              className="p-4 bg-slate-900/40 hover:bg-indigo-500/[0.04] border border-white/[0.02] hover:border-indigo-500/20 rounded-xl cursor-pointer transition-colors flex items-center justify-between group shadow-sm"
            >
              <div className="space-y-0.5">
                <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest">{s.label}</span>
                <p className="text-xs font-medium text-slate-300 leading-normal">{s.text}</p>
              </div>
              <ChevronRight size={16} className="text-slate-500 group-hover:text-indigo-400 transition-colors transform group-hover:translate-x-0.5" />
            </motion.div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
}

function StatCard({ icon, title, value, desc }) {
  return (
    <motion.div 
      variants={{ hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0 } }}
      whileHover={{ y: -2 }}
      className="p-4 glass-card glow-hover flex items-start gap-3 border border-white/[0.02]"
    >
      <div className="p-2.5 bg-slate-800/60 rounded-xl border border-white/[0.04] shrink-0">
        {icon}
      </div>
      <div className="min-w-0">
        <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest block">{title}</span>
        <h5 className="text-sm font-semibold text-slate-200 mt-0.5 truncate">{value}</h5>
        <p className="text-[10px] text-slate-400 mt-0.5 truncate">{desc}</p>
      </div>
    </motion.div>
  );
}
